// 路由 Store：负责常量路由/权限路由初始化、菜单与面包屑生成、路由缓存控制与动态路由挂载/卸载
import { computed, nextTick, ref, shallowRef } from 'vue';
import type { RouteRecordRaw } from 'vue-router';
import { defineStore } from 'pinia';
import { useBoolean } from '@sa/hooks';
import type { CustomRoute, ElegantConstRoute, LastLevelRouteKey, RouteKey, RouteMap } from '@elegant-router/types';
import { router } from '@/router';
import { fetchGetConstantRoutes, fetchGetUserRoutes, fetchIsRouteExist } from '@/service/api';
import { SetupStoreId } from '@/enum';
import { createStaticRoutes, getAuthVueRoutes } from '@/router/routes';
import { ROOT_ROUTE } from '@/router/routes/builtin';
import { getRouteName, getRoutePath } from '@/router/elegant/transform';
import { useAuthStore } from '../auth';
import { useTabStore } from '../tab';
import {
  filterAuthRoutesByRoles,
  getBreadcrumbsByRoute,
  getCacheRouteNames,
  getGlobalMenusByAuthRoutes,
  getSelectedMenuKeyPathByKey,
  isRouteExistByRouteName,
  sortRoutesByOrder,
  transformMenuToSearchMenus,
  updateLocaleOfGlobalMenus
} from './shared';

// 创建路由 Store（中文说明：内部使用 setup 语法，配合 resetSetupStore 插件支持 $reset）
export const useRouteStore = defineStore(SetupStoreId.Route, () => {
  // 获取鉴权 Store（用于读取用户信息与角色）
  const authStore = useAuthStore();
  // 获取标签页 Store（用于初始化首页 Tab）
  const tabStore = useTabStore();
  // 常量路由初始化标记与设置方法
  const { bool: isInitConstantRoute, setBool: setIsInitConstantRoute } = useBoolean();
  // 权限路由初始化标记与设置方法
  const { bool: isInitAuthRoute, setBool: setIsInitAuthRoute } = useBoolean();

  /**
   * Auth route mode
   *
   * It recommends to use static mode in the development environment, and use dynamic mode in the production
   * environment, if use static mode in development environment, the auth routes will be auto generated by plugin
   * "@elegant-router/vue"
   */
  // 权限路由模式（中文说明：static 使用本地生成路由，dynamic 从后端拉取）
  const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE);

  /** Home route key */
  // 首页路由 key（中文说明：用于确定默认首页 Tab 与 root 重定向）
  const routeHome = ref(import.meta.env.VITE_ROUTE_HOME);

  /**
   * Set route home
   *
   * @param routeKey Route key
   */
  // 设置首页路由 key（中文说明：动态路由模式下由后端返回 home 时调用）
  function setRouteHome(routeKey: LastLevelRouteKey) {
    // 更新首页路由 key
    routeHome.value = routeKey;
    // setRouteHome 函数结束
  }

  /** constant routes */
  // 常量路由列表（中文说明：如登录/错误页等无需权限的路由）
  const constantRoutes = shallowRef<ElegantConstRoute[]>([]);

  // 添加常量路由（中文说明：通过 Map 去重后写入 constantRoutes）
  function addConstantRoutes(routes: ElegantConstRoute[]) {
    // 常量路由 Map（用于按 name 去重）
    const constantRoutesMap = new Map<string, ElegantConstRoute>([]);

    // 遍历 routes 并写入 Map
    routes.forEach(route => {
      // 按路由 name 去重写入
      constantRoutesMap.set(route.name, route);
      // forEach 单次迭代结束
    });

    // 将去重后的路由写入响应式引用
    constantRoutes.value = Array.from(constantRoutesMap.values());
    // addConstantRoutes 函数结束
  }

  /** auth routes */
  // 权限路由列表（中文说明：需要权限控制的路由）
  const authRoutes = shallowRef<ElegantConstRoute[]>([]);

  // 添加权限路由（中文说明：通过 Map 去重后写入 authRoutes）
  function addAuthRoutes(routes: ElegantConstRoute[]) {
    // 权限路由 Map（用于按 name 去重）
    const authRoutesMap = new Map<string, ElegantConstRoute>([]);

    // 遍历 routes 并写入 Map
    routes.forEach(route => {
      // 按路由 name 去重写入
      authRoutesMap.set(route.name, route);
      // forEach 单次迭代结束
    });

    // 将去重后的路由写入响应式引用
    authRoutes.value = Array.from(authRoutesMap.values());
    // addAuthRoutes 函数结束
  }

  // 保存动态添加到 vue-router 的移除函数（用于 reset 时卸载动态路由）
  const removeRouteFns: (() => void)[] = [];

  /** Global menus */
  // 全局菜单列表（中文说明：由权限路由转换得到）
  const menus = ref<App.Global.Menu[]>([]);
  // 搜索菜单（中文说明：将树形菜单拍平成可搜索列表）
  const searchMenus = computed(() => transformMenuToSearchMenus(menus.value));

  /** Get global menus */
  // 根据权限路由生成全局菜单（中文说明：过滤 hideInMenu，并生成 children）
  function getGlobalMenus(routes: ElegantConstRoute[]) {
    // 写入由 routes 转换得到的菜单
    menus.value = getGlobalMenusByAuthRoutes(routes);
    // getGlobalMenus 函数结束
  }

  /** Update global menus by locale */
  // 语言变化时更新菜单文案（中文说明：按 i18nKey 重新生成 label）
  function updateGlobalMenusByLocale() {
    // 更新 menus 文案
    menus.value = updateLocaleOfGlobalMenus(menus.value);
    // updateGlobalMenusByLocale 函数结束
  }

  /** Cache routes */
  // keep-alive 缓存路由 name 列表（中文说明：由路由 meta.keepAlive 生成）
  const cacheRoutes = ref<RouteKey[]>([]);

  /**
   * Exclude cache routes
   *
   * for reset route cache
   */
  // 临时排除缓存的路由 name 列表（中文说明：用于触发 keep-alive 刷新）
  const excludeCacheRoutes = ref<RouteKey[]>([]);

  /**
   * Get cache routes
   *
   * @param routes Vue routes
   */
  // 生成需要缓存的路由 name 列表（中文说明：根据路由结构与 keepAlive 标记提取）
  function getCacheRoutes(routes: RouteRecordRaw[]) {
    // 写入缓存路由 name 列表
    cacheRoutes.value = getCacheRouteNames(routes);
    // getCacheRoutes 函数结束
  }

  /**
   * Reset route cache
   *
   * @default router.currentRoute.value.name current route name
   * @param routeKey
   */
  // 重置某个路由的 keep-alive 缓存（中文说明：将路由 name 放入 excludeCacheRoutes，nextTick 后清空）
  async function resetRouteCache(routeKey?: RouteKey) {
    // 计算要重置的路由 name（默认使用当前路由）
    const routeName = routeKey || (router.currentRoute.value.name as RouteKey);

    // 将路由 name 写入排除列表，触发 keep-alive 重建
    excludeCacheRoutes.value.push(routeName);

    // 等待下一次渲染，让排除生效
    await nextTick();

    // 清空排除列表，恢复正常缓存策略
    excludeCacheRoutes.value = [];
    // resetRouteCache 函数结束
  }

  /** Global breadcrumbs */
  // 面包屑（中文说明：根据当前路由与菜单树生成）
  const breadcrumbs = computed(() => getBreadcrumbsByRoute(router.currentRoute.value, menus.value));

  /** Reset store */
  // 重置路由 Store（中文说明：重置自身状态、卸载动态路由，并重新初始化常量路由）
  async function resetStore() {
    // 获取自身 store 实例（用于 $reset）
    const routeStore = useRouteStore();

    // 重置 store 状态到初始值
    routeStore.$reset();

    // 卸载已动态添加的路由
    resetVueRoutes();

    // after reset store, need to re-init constant route
    // 重置后需要重新初始化常量路由
    await initConstantRoute();
    // resetStore 函数结束
  }

  /** Reset vue routes */
  // 卸载动态添加的 vue-router 路由（中文说明：执行所有 removeRouteFns 并清空数组）
  function resetVueRoutes() {
    // 依次执行移除函数
    removeRouteFns.forEach(fn => fn());
    // 清空移除函数列表
    removeRouteFns.length = 0;
    // resetVueRoutes 函数结束
  }

  /** init constant route */
  // 初始化常量路由（中文说明：根据 static/dynamic 模式获取常量路由，并生成菜单与缓存信息）
  async function initConstantRoute() {
    // 已初始化则直接返回
    if (isInitConstantRoute.value) return;

    // 创建静态路由（包含 constantRoutes 与 authRoutes）
    const staticRoute = createStaticRoutes();

    // 静态模式直接使用静态常量路由
    if (authRouteMode.value === 'static') {
      // 添加静态常量路由
      addConstantRoutes(staticRoute.constantRoutes);
    } else {
      // 动态模式从后端获取常量路由
      const { data, error } = await fetchGetConstantRoutes();

      // 获取成功则使用后端常量路由，否则回退到静态常量路由
      if (!error) {
        // 添加后端常量路由
        addConstantRoutes(data);
      } else {
        // if fetch constant routes failed, use static constant routes
        // 后端获取失败时回退使用静态常量路由
        addConstantRoutes(staticRoute.constantRoutes);
        // error 分支结束
      }
      // authRouteMode 分支结束
    }

    // 合并常量与权限路由，挂载到 vue-router 并生成菜单与缓存信息
    handleConstantAndAuthRoutes();

    // 标记常量路由已初始化
    setIsInitConstantRoute(true);

    // 初始化首页 Tab
    tabStore.initHomeTab();
    // initConstantRoute 函数结束
  }

  /** Init auth route */
  // 初始化权限路由（中文说明：确保用户信息已初始化，然后按模式初始化静态/动态权限路由）
  async function initAuthRoute() {
    // check if user info is initialized
    // 若用户信息未初始化，先初始化用户信息
    if (!authStore.userInfo.userId) {
      // 初始化用户信息（会从本地 token 恢复并拉取 userInfo）
      await authStore.initUserInfo();
      // userId 判断分支结束
    }

    // 按权限路由模式初始化
    if (authRouteMode.value === 'static') {
      // 初始化静态权限路由
      initStaticAuthRoute();
    } else {
      // 初始化动态权限路由
      await initDynamicAuthRoute();
      // authRouteMode 分支结束
    }

    // 初始化首页 Tab
    tabStore.initHomeTab();
    // initAuthRoute 函数结束
  }

  /** Init static auth route */
  // 初始化静态权限路由（中文说明：超级角色拿全部路由，否则按 roles 过滤）
  function initStaticAuthRoute() {
    // 获取静态权限路由
    const { authRoutes: staticAuthRoutes } = createStaticRoutes();

    // 静态超级角色：不做过滤
    if (authStore.isStaticSuper) {
      // 添加全部静态权限路由
      addAuthRoutes(staticAuthRoutes);
    } else {
      // 非超级角色：按用户角色过滤静态权限路由
      const filteredAuthRoutes = filterAuthRoutesByRoles(staticAuthRoutes, authStore.userInfo.roles);

      // 添加过滤后的权限路由
      addAuthRoutes(filteredAuthRoutes);
      // isStaticSuper 分支结束
    }

    // 合并常量与权限路由，挂载到 vue-router 并生成菜单与缓存信息
    handleConstantAndAuthRoutes();

    // 标记权限路由已初始化
    setIsInitAuthRoute(true);
    // initStaticAuthRoute 函数结束
  }

  /** Init dynamic auth route */
  // 初始化动态权限路由（中文说明：从后端拉取 routes/home，挂载路由并更新 root 重定向）
  async function initDynamicAuthRoute() {
    // 从后端获取用户路由
    const { data, error } = await fetchGetUserRoutes();

    // 获取成功则处理动态路由
    if (!error) {
      // 解构后端返回的 routes 与 home
      const { routes, home } = data;

      // 添加后端返回的权限路由
      addAuthRoutes(routes);

      // 合并常量与权限路由，挂载到 vue-router 并生成菜单与缓存信息
      handleConstantAndAuthRoutes();

      // 更新首页路由 key
      setRouteHome(home);

      // 动态模式下更新 root 路由重定向
      handleUpdateRootRouteRedirect(home);

      // 标记权限路由已初始化
      setIsInitAuthRoute(true);
    } else {
      // if fetch user routes failed, reset store
      // 获取用户路由失败时重置鉴权状态（会跳转登录等）
      authStore.resetStore();
      // error 分支结束
    }
    // initDynamicAuthRoute 函数结束
  }

  /** handle constant and auth routes */
  // 合并并处理常量/权限路由（中文说明：排序、转换为 vueRoutes、挂载到 router、生成菜单与缓存列表）
  function handleConstantAndAuthRoutes() {
    // 合并常量路由与权限路由
    const allRoutes = [...constantRoutes.value, ...authRoutes.value];

    // 按 meta.order 进行排序
    const sortRoutes = sortRoutesByOrder(allRoutes);

    // 将 Elegant 路由转换为 vue-router RouteRecordRaw
    const vueRoutes = getAuthVueRoutes(sortRoutes);

    // 先卸载旧的动态路由
    resetVueRoutes();

    // 将新路由添加到 vue-router
    addRoutesToVueRouter(vueRoutes);

    // 生成全局菜单
    getGlobalMenus(sortRoutes);

    // 生成缓存路由 name 列表
    getCacheRoutes(vueRoutes);
    // handleConstantAndAuthRoutes 函数结束
  }

  /**
   * Add routes to vue router
   *
   * @param routes Vue routes
   */
  // 将路由数组添加到 vue-router（中文说明：记录 removeFn 以便重置时卸载）
  function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
    // 遍历每个路由并添加到 router
    routes.forEach(route => {
      // addRoute 返回 removeFn，可用于后续移除该路由
      const removeFn = router.addRoute(route);
      // 保存 removeFn
      addRemoveRouteFn(removeFn);
      // forEach 单次迭代结束
    });
    // addRoutesToVueRouter 函数结束
  }

  /**
   * Add remove route fn
   *
   * @param fn
   */
  // 记录移除路由的函数（中文说明：用于 resetVueRoutes 时批量卸载）
  function addRemoveRouteFn(fn: () => void) {
    // 写入移除函数列表
    removeRouteFns.push(fn);
    // addRemoveRouteFn 函数结束
  }

  /**
   * Update root route redirect when auth route mode is dynamic
   *
   * @param redirectKey Redirect route key
   */
  // 动态模式下更新 root 路由重定向（中文说明：将 ROOT_ROUTE 的 redirect 指向 home）
  function handleUpdateRootRouteRedirect(redirectKey: LastLevelRouteKey) {
    // 由 redirectKey 计算目标 path
    const redirect = getRoutePath(redirectKey);

    // redirect 存在时才更新 root 路由
    if (redirect) {
      // 创建新的 root 路由对象并设置 redirect
      const rootRoute: CustomRoute = { ...ROOT_ROUTE, redirect };

      // 先移除旧的 root 路由
      router.removeRoute(rootRoute.name);

      // 将 Elegant rootRoute 转换为 vue-router 路由记录
      const [rootVueRoute] = getAuthVueRoutes([rootRoute]);

      // 重新添加 root 路由
      router.addRoute(rootVueRoute);
      // redirect 分支结束
    }
    // handleUpdateRootRouteRedirect 函数结束
  }

  /**
   * Get is auth route exist
   *
   * @param routePath Route path
   */
  // 判断某个权限路由是否存在（中文说明：静态模式本地判断，动态模式请求后端判断）
  async function getIsAuthRouteExist(routePath: RouteMap[RouteKey]) {
    // 由 routePath 反查路由 name
    const routeName = getRouteName(routePath);

    // 无法解析 routeName 时直接返回 false
    if (!routeName) {
      // 返回不存在
      return false;
      // routeName 判断分支结束
    }

    // 静态模式：在静态权限路由中判断是否存在
    if (authRouteMode.value === 'static') {
      // 获取静态权限路由
      const { authRoutes: staticAuthRoutes } = createStaticRoutes();
      // 返回是否存在
      return isRouteExistByRouteName(routeName, staticAuthRoutes);
      // static 分支结束
    }

    // 动态模式：请求后端判断路由是否存在
    const { data } = await fetchIsRouteExist(routeName);

    // 返回后端判断结果
    return data;
    // getIsAuthRouteExist 函数结束
  }

  /**
   * Get selected menu key path
   *
   * @param selectedKey Selected menu key
   */
  // 获取选中菜单的 keyPath（中文说明：用于展开父级菜单）
  function getSelectedMenuKeyPath(selectedKey: string) {
    // 使用菜单树计算 keyPath
    return getSelectedMenuKeyPathByKey(selectedKey, menus.value);
    // getSelectedMenuKeyPath 函数结束
  }

  // 已登录时路由切换的全局钩子（中文说明：预留扩展点）
  async function onRouteSwitchWhenLoggedIn() {
    // some global init logic when logged in and switch route
    // 当前暂无实现
    // onRouteSwitchWhenLoggedIn 函数结束
  }

  // 未登录但可访问路由时的全局钩子（中文说明：预留扩展点）
  async function onRouteSwitchWhenNotLoggedIn() {
    // some global init logic if it does not need to be logged in
    // 当前暂无实现
    // onRouteSwitchWhenNotLoggedIn 函数结束
  }

  // 对外暴露路由相关状态与方法
  return {
    // 重置路由 Store
    resetStore,
    // 首页路由 key
    routeHome,
    // 全局菜单
    menus,
    // 搜索菜单
    searchMenus,
    // 按语言更新菜单
    updateGlobalMenusByLocale,
    // 缓存路由列表
    cacheRoutes,
    // 临时排除缓存路由列表
    excludeCacheRoutes,
    // 重置路由缓存方法
    resetRouteCache,
    // 面包屑列表
    breadcrumbs,
    // 初始化常量路由
    initConstantRoute,
    // 常量路由初始化标记
    isInitConstantRoute,
    // 初始化权限路由
    initAuthRoute,
    // 权限路由初始化标记
    isInitAuthRoute,
    // 设置权限路由初始化标记
    setIsInitAuthRoute,
    // 判断权限路由是否存在
    getIsAuthRouteExist,
    // 获取选中菜单 keyPath
    getSelectedMenuKeyPath,
    // 登录后路由切换钩子
    onRouteSwitchWhenLoggedIn,
    // 未登录路由切换钩子
    onRouteSwitchWhenNotLoggedIn
    // 返回对象定义结束
  };
  // useRouteStore setup 回调结束
});
